name: e2e

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 1) install root deps (playwright, concurrently, tsx, etc.)
      - name: Install root deps
        run: npm ci

      # 2) install frontend deps (vite, react, @vitejs/plugin-react, etc.)
      - name: Install frontend deps
        run: npm --prefix frontend ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 3) run tests with extra logging for the webServer startup
      - name: Run E2E tests (Chromium)
        run: DEBUG=pw:webserver npx playwright test --project=chromium

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
